package com.unsa.PhotoSharing.persistence.entity;

// default package
// Generated 03-jun-2014 9:20:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Comentarios generated by hbm2java
 */
public class Comentarios implements java.io.Serializable {

	private Integer idComentario;
	private Fotos fotos;
	private Usuario usuario;
	private String comentario;
	private Date comentDate;

	public Comentarios() {
	}

	public Comentarios(Fotos fotos, Usuario usuario) {
		this.fotos = fotos;
		this.usuario = usuario;
	}

	public Comentarios(Fotos fotos, Usuario usuario, String comentario,
			Date comentDate) {
		this.fotos = fotos;
		this.usuario = usuario;
		this.comentario = comentario;
		this.comentDate = comentDate;
	}

	public Integer getIdComentario() {
		return this.idComentario;
	}

	public void setIdComentario(Integer idComentario) {
		this.idComentario = idComentario;
	}

	public Fotos getFotos() {
		return this.fotos;
	}

	public void setFotos(Fotos fotos) {
		this.fotos = fotos;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getComentDate() {
		return this.comentDate;
	}

	public void setComentDate(Date comentDate) {
		this.comentDate = comentDate;
	}

}
