// default package
// Generated 03-jun-2014 9:20:39 by Hibernate Tools 3.4.0.CR1
package com.unsa.PhotoSharing.persistence.entity;
/**
 * Likes generated by hbm2java
 */
public class Likes implements java.io.Serializable {

	private LikesId id;
	private Fotos fotos;
	private Usuario usuario;
	private Boolean liked;

	public Likes() {
	}

	public Likes(LikesId id, Fotos fotos, Usuario usuario) {
		this.id = id;
		this.fotos = fotos;
		this.usuario = usuario;
	}

	public Likes(LikesId id, Fotos fotos, Usuario usuario, Boolean liked) {
		this.id = id;
		this.fotos = fotos;
		this.usuario = usuario;
		this.liked = liked;
	}

	public LikesId getId() {
		return this.id;
	}

	public void setId(LikesId id) {
		this.id = id;
	}

	public Fotos getFotos() {
		return this.fotos;
	}

	public void setFotos(Fotos fotos) {
		this.fotos = fotos;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Boolean getLiked() {
		return this.liked;
	}

	public void setLiked(Boolean liked) {
		this.liked = liked;
	}

}
