// default package
// Generated 03-jun-2014 9:20:39 by Hibernate Tools 3.4.0.CR1
package com.unsa.PhotoSharing.persistence.entity;
/**
 * LikesId generated by hbm2java
 */
public class LikesId implements java.io.Serializable {

	private int idUsuario;
	private int idFoto;

	public LikesId() {
	}

	public LikesId(int idUsuario, int idFoto) {
		this.idUsuario = idUsuario;
		this.idFoto = idFoto;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdFoto() {
		return this.idFoto;
	}

	public void setIdFoto(int idFoto) {
		this.idFoto = idFoto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LikesId))
			return false;
		LikesId castOther = (LikesId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdFoto() == castOther.getIdFoto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdFoto();
		return result;
	}

}
