// default package
// Generated 03-jun-2014 9:20:39 by Hibernate Tools 3.4.0.CR1
package com.unsa.PhotoSharing.persistence.entity;
/**
 * Tags generated by hbm2java
 */
public class Tags implements java.io.Serializable {

	private Integer idTags;
	private Fotos fotos;
	private String nombreTag;

	public Tags() {
	}

	public Tags(Fotos fotos) {
		this.fotos = fotos;
	}

	public Tags(Fotos fotos, String nombreTag) {
		this.fotos = fotos;
		this.nombreTag = nombreTag;
	}

	public Integer getIdTags() {
		return this.idTags;
	}

	public void setIdTags(Integer idTags) {
		this.idTags = idTags;
	}

	public Fotos getFotos() {
		return this.fotos;
	}

	public void setFotos(Fotos fotos) {
		this.fotos = fotos;
	}

	public String getNombreTag() {
		return this.nombreTag;
	}

	public void setNombreTag(String nombreTag) {
		this.nombreTag = nombreTag;
	}

}
