// default package
// Generated 03-jun-2014 9:20:39 by Hibernate Tools 3.4.0.CR1
package com.unsa.PhotoSharing.persistence.entity;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String nombre;
	private String apellidos;
	private String nickname;
	private String email;
	private String password;
	private String profilePhoto;
	private Set<Comentarios> comentarioses = new HashSet<Comentarios>(0);
	private Set<Usuario> usuariosForIdUsuario1 = new HashSet<Usuario>(0);
	private Set<Usuario> usuariosForIdUsuario2 = new HashSet<Usuario>(0);
	private Set<Likes> likeses = new HashSet<Likes>(0);
	private Set<Fotos> fotoses = new HashSet<Fotos>(0);

	public Usuario() {
	}

	public Usuario(String nombre, String apellidos, String nickname,
			String email, String password, String profilePhoto,
			Set<Comentarios> comentarioses, Set<Usuario> usuariosForIdUsuario1,
			Set<Usuario> usuariosForIdUsuario2, Set<Likes> likeses,
			Set<Fotos> fotoses) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.nickname = nickname;
		this.email = email;
		this.password = password;
		this.profilePhoto = profilePhoto;
		this.comentarioses = comentarioses;
		this.usuariosForIdUsuario1 = usuariosForIdUsuario1;
		this.usuariosForIdUsuario2 = usuariosForIdUsuario2;
		this.likeses = likeses;
		this.fotoses = fotoses;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getProfilePhoto() {
		return this.profilePhoto;
	}

	public void setProfilePhoto(String profilePhoto) {
		this.profilePhoto = profilePhoto;
	}

	public Set<Comentarios> getComentarioses() {
		return this.comentarioses;
	}

	public void setComentarioses(Set<Comentarios> comentarioses) {
		this.comentarioses = comentarioses;
	}

	public Set<Usuario> getUsuariosForIdUsuario1() {
		return this.usuariosForIdUsuario1;
	}

	public void setUsuariosForIdUsuario1(Set<Usuario> usuariosForIdUsuario1) {
		this.usuariosForIdUsuario1 = usuariosForIdUsuario1;
	}

	public Set<Usuario> getUsuariosForIdUsuario2() {
		return this.usuariosForIdUsuario2;
	}

	public void setUsuariosForIdUsuario2(Set<Usuario> usuariosForIdUsuario2) {
		this.usuariosForIdUsuario2 = usuariosForIdUsuario2;
	}

	public Set<Likes> getLikeses() {
		return this.likeses;
	}

	public void setLikeses(Set<Likes> likeses) {
		this.likeses = likeses;
	}

	public Set<Fotos> getFotoses() {
		return this.fotoses;
	}

	public void setFotoses(Set<Fotos> fotoses) {
		this.fotoses = fotoses;
	}

}
